<?php
$form = $this->form;
$fieldset = $form->get('post');

$username = $fieldset->get('username');
$username->setAttribute('class', 'form-control');
$username->setAttribute('placeholder', 'Enter User Name');

$reason = $fieldset->get('reason');
$reason->setAttribute('class', 'form-control');
$reason->setAttribute('placeholder', 'Enter Reason');

$bookingdate = $fieldset->get('bookingdate');
$bookingdate->setAttribute('class', 'form-control');
$bookingdate->setAttribute('placeholder', 'Select Booking Date');

$submit = $form->get('submit');
$submit->setValue($this->submitLabel);
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>

    <fieldset>
        <div class="form-group">
            <?= $this->formLabel($username) ?>
            <?= $this->formElement($username) ?>
            <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($reason) ?>
            <?= $this->formElement($reason) ?>
            <?= $this->formElementErrors()->render($reason, ['class' => 'help-block']) ?>
        </div>
		
		<div class="form-group">
            <?= $this->formLabel($bookingdate) ?>
            <?= $this->formElement($bookingdate) ?>
            <?= $this->formElementErrors()->render($bookingdate, ['class' => 'help-block']) ?>
        </div>
		
    </fieldset>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($fieldset->get('id'));
echo $this->form()->closeTag();