apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      app: ui
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: ui:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
