<?php $this->headTitle('Save Doctor Profile'); ?>

<div class="jumbotron">
    <h1>Your registration  <span class="zf-green">successfully done</span></h1>
    <p>
        <?php echo $this->siteName; ?>
        <a href="https://github.com/zendframework/zend-expressive-skeleton" target="_blank">team </a>.
        Congrats You!
    </p>
    
</div>

<div class="row">
    <div class="col-md-4">
        <h2>
            <a href="/"> Home Appointment </a>
			<a href="/createappointment"> Create Appointment </a>
			<a href="/viewappointment"> View Appointment </a>
			<a href="/updateappointment"> Update Appointment </a>
			<a href="/deleteappointment"> Delete Appointment </a>
        </h2>
    </div>

</div>
