<?php
use Appointment\Form\AppointmentDataForm;

/** @var AppointmentDataForm $form */
$form = $this->appointmentForm;
$form->setAttribute('action', $this->url('appointment-create-handle'));

$this->headTitle('Create new appointment');
?>

<div class="jumbotron">
    <h1>Create new appointment</h1>
</div>

<div class="alert alert-danger">
    <strong><?= $this->message ?></strong>
</div>

<div class="well">
    <?= $this->form()->openTag($form) ?>
    
    <div class="form-group">
        <?= $this->formLabel($form->get('username')) ?>
        <div class="col-sm-10">
            <?= $this->formElement($form->get('username')) ?>
            <?= $this->formElementErrors($form->get('username')) ?>
        </div>
    </div>
	
	
	<div class="form-group">
        <?= $this->formLabel($form->get('reason')) ?>
        <div class="col-sm-10">
            <?= $this->formElement($form->get('reason')) ?>
            <?= $this->formElementErrors($form->get('reason')) ?>
        </div>
    </div>
	
	
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?= $this->formElement($form->get('save_appointment')) ?>
        </div>
    </div>
    <?= $this->form()->closeTag() ?>
</div>

<p>
    <a href="<?= $this->url('appointment') ?>" class="btn btn-success">
        Back to appointment list
    </a>
</p>
